<ROWSET>
 <ROW>
  <CODE>1</CODE>
  <CODE_VALUE>IS EQUAL</CODE_VALUE>
 </ROW>
 <ROW>
  <CODE>2</CODE>
  <CODE_VALUE>IS AFTER</CODE_VALUE>
 </ROW>
 <ROW>
  <CODE>3</CODE>
  <CODE_VALUE>IS BEFORE</CODE_VALUE>
 </ROW>
 <ROW>
  <CODE>4</CODE>
  <CODE_VALUE>IS BETWEEN</CODE_VALUE>
 </ROW>
  <ROW>
  <CODE>5</CODE>
  <CODE_VALUE>IS TODAY</CODE_VALUE>
 </ROW>
  <ROW>
  <CODE>6</CODE>
  <CODE_VALUE>BEFORE TODAY</CODE_VALUE>
 </ROW>
  <ROW>
  <CODE>7</CODE>
  <CODE_VALUE>AFTER TODAY</CODE_VALUE>
 </ROW>
  <ROW>
  <CODE>8</CODE>
  <CODE_VALUE>THIS WEEK</CODE_VALUE>
 </ROW>
  <ROW>
  <CODE>9</CODE>
  <CODE_VALUE>THIS MONTH</CODE_VALUE>
 </ROW>
   <ROW>
  <CODE>10</CODE>
  <CODE_VALUE>THIS YEAR</CODE_VALUE>
 </ROW>
</ROWSET>