<ROWSET>
 <ROW>
  <CODE>1</CODE>
  <CODE_VALUE>EQUALS</CODE_VALUE>
 </ROW>
 <ROW>
  <CODE>2</CODE>
  <CODE_VALUE>LESS THAN</CODE_VALUE>
 </ROW>
 <ROW>
  <CODE>3</CODE>
  <CODE_VALUE>GREATER THAN</CODE_VALUE>
 </ROW>
  <ROW>
  <CODE>4</CODE>
  <CODE_VALUE>LESS THAN OR EQUAL TO</CODE_VALUE>
 </ROW>
 <ROW>
  <CODE>5</CODE>
  <CODE_VALUE>GREATER THAN OR EQUAL TO</CODE_VALUE>
 </ROW>
  <ROW>
  <CODE>6</CODE>
  <CODE_VALUE>DOES NOT EQUAL</CODE_VALUE>
 </ROW>
</ROWSET>

