<ROWSET>
 <ROW>
  <CODE>1</CODE>
  <CODE_VALUE>IS EQUAL TO</CODE_VALUE>
 </ROW>
 <ROW>
  <CODE>2</CODE>
  <CODE_VALUE>IS NOT EQUAL TO</CODE_VALUE>
 </ROW>
 <ROW>
  <CODE>3</CODE>
  <CODE_VALUE>BEGINS WITH</CODE_VALUE>
 </ROW>
  <ROW>
  <CODE>4</CODE>
  <CODE_VALUE>DOES NOT BEGINS WITH</CODE_VALUE>
 </ROW>
 <ROW>
  <CODE>5</CODE>
  <CODE_VALUE>CONTAINS</CODE_VALUE>
 </ROW>
  <ROW>
  <CODE>6</CODE>
  <CODE_VALUE>DOES NOT CONTAIN</CODE_VALUE>
 </ROW>
  <ROW>
  <CODE>7</CODE>
  <CODE_VALUE>IS NULL</CODE_VALUE>
 </ROW>
</ROWSET>