<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.1"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:fo="http://www.w3.org/1999/XSL/Format" 
	xmlns:datetime="http://exslt.org/dates-and-times"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	exclude-result-prefixes="fo datetime">

  <xsl:template match="ROWSET">
<fo:root xmlns:fo="http://www.w3.org/1999/XSL/Format">
  
  <fo:layout-master-set>
  	<fo:simple-page-master master-name="A4" page-height="21cm" page-width="28.4cm">
  		<fo:region-body margin="1cm"/>
  		<fo:region-before region-name="header-audit" extent="0.5cm"/>
  		<fo:region-after region-name="footer-audit" extent="0.5cm"/>
  		<fo:region-start extent="0.5cm"/>
  		<fo:region-end extent="0.5cm"/>
	</fo:simple-page-master>
</fo:layout-master-set>

<fo:page-sequence master-reference="A4">
	
	<xsl:variable name="date" select="datetime:dateTime() cast as xs:dateTime"/>
	<fo:static-content flow-name="footer-audit">
		<fo:block font-size="10pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" line-height="13pt" margin-left="0.2cm" margin-right="0.2cm">
			<fo:table>
				<fo:table-body>
					<fo:table-row>
						<fo:table-cell>
							<fo:block text-align-last="left">
								<xsl:text>Report Generated By: </xsl:text><xsl:value-of select="/ROWSET/ROW/REPORT/REPORTSUMMARY/USER"/>
							</fo:block>
						</fo:table-cell>
						<fo:table-cell>
							<fo:block text-align-last="left">
								<xsl:text>Report Generated Time: </xsl:text>								
								<xsl:value-of select="format-dateTime($date, '[Y]-[M01]-[D01]T[H01]:[m01]:[s01][PN,*-2] [ZN,*-3]', (), (), 'us')" />
							</fo:block>
						</fo:table-cell>
						<fo:table-cell text-align-last="right">
							<fo:block margin-bottom="0.2cm">Page:<fo:page-number></fo:page-number></fo:block>
						</fo:table-cell>
					</fo:table-row>
				</fo:table-body>
			</fo:table>			
		</fo:block>
    </fo:static-content>
	
	<fo:static-content flow-name="header-audit">
		<fo:block text-align-last="left" margin-left="0.5cm" font-size="10pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" line-height="13pt" margin-top="0.1cm">
			<xsl:text>Audit History Report - PRIMO Report ID: </xsl:text><xsl:value-of select="/ROWSET/ROW/REPORT/REPORTSUMMARY/REPORTID"/>
		</fo:block>
    </fo:static-content>
  
  <fo:flow flow-name="xsl-region-body">
  
  	<!-- ************************************ PRIMO REPORT ************************************ -->
  	
  	<fo:block font-size="14pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" color="#008080" font-weight="bold">
		<xsl:text>PRIMO REPORT AUDIT LOG</xsl:text>
	  </fo:block>
    <fo:block font-size="10pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" font-weight="bold" color="#FF8040">
      <xsl:text>Report ID:</xsl:text>
      <xsl:value-of select="/ROWSET/ROW/REPORT/REPORTSUMMARY/REPORTID"/>
    </fo:block>
    <fo:block font-size="8pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" line-height="13pt" border-width="1pt" border-style="solid" border-color="#CCCCCC">
      <fo:table margin="3pt">
        <fo:table-body>
          <fo:table-row>
			<fo:table-cell width="110pt">
              <fo:block font-weight="bold" color="#FF8040">Update Timestamp</fo:block>
            </fo:table-cell>
            <fo:table-cell width="90pt">
              <fo:block font-weight="bold" color="#FF8040">Activity Type</fo:block>
            </fo:table-cell>
            <fo:table-cell width="80pt">
              <fo:block font-weight="bold" color="#FF8040">Update User</fo:block>
            </fo:table-cell>            
            <fo:table-cell>
              <fo:block font-weight="bold" color="#FF8040">Reason for change</fo:block>
            </fo:table-cell>
          </fo:table-row>
          <xsl:for-each select="/ROWSET/ROW/REPORT/REPORTSUMMARY/REPORTSUMMARY_T">
            <xsl:variable name="REPORTSUMMARY_T" select="."/>
            <fo:table-row space-after="10pt">
              <fo:table-cell font-weight="normal" width="110pt">
                <fo:block>
                  <xsl:value-of select="UPDATEDTS"/>
                </fo:block>
              </fo:table-cell>
			  <fo:table-cell font-weight="normal" width="90pt">
                <fo:block>
                  <xsl:value-of select="ACTIVITYTYPE"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal" width="80pt">
                <fo:block>
                  <xsl:value-of select="UPDATEUSER"/>
                </fo:block>
              </fo:table-cell>              
              <fo:table-cell font-weight="normal">
                <fo:block>
                  <xsl:value-of select="REASON"/>
                </fo:block>
              </fo:table-cell>
            </fo:table-row>
          </xsl:for-each>
        </fo:table-body>
      </fo:table>
    </fo:block>
	
	
	<!-- ************************************ REPORTS SECTION ************************************ -->
  	<fo:block font-size="14pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" color="#008080" font-weight="bold" space-before="10pt">
      <xsl:text>REPORT SUMMARY</xsl:text>    
    </fo:block>
    <fo:block font-size="8pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" line-height="13pt" border-width="1pt" border-style="solid" border-color="#CCCCCC">
      <fo:table margin="3pt">
        <fo:table-body>
          <fo:table-row>
            <fo:table-cell margin="3pt" width="100pt">
              <fo:block font-weight="bold" color="#FF8040">Update TS</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="30pt">
              <fo:block font-weight="bold" color="#FF8040">Action</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="80pt">
              <fo:block font-weight="bold" color="#FF8040">Updated By</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="170pt">
              <fo:block font-weight="bold" color="#FF8040">Column</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="60pt">
              <fo:block font-weight="bold" color="#FF8040">PK1</fo:block>
            </fo:table-cell>
            <fo:table-cell>
              <fo:block font-weight="bold" color="#FF8040">From</fo:block>
            </fo:table-cell>
            <fo:table-cell>
              <fo:block font-weight="bold" color="#FF8040">To</fo:block>
            </fo:table-cell>
          </fo:table-row>
		  
		  <xsl:for-each select="/ROWSET/ROW/REPORT/REPORTS/REPORTS_T">
            <xsl:variable name="REPORTS_T" select="."/> 
          <fo:table-row space-after="10pt">
            <fo:table-cell font-weight="normal" width="100pt">
              <fo:block>
                <xsl:value-of select="UPDATEDTS"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal" width="30pt">
              <fo:block>
                <xsl:value-of select="ACTION"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal" width="80pt">
              <fo:block>
                <xsl:value-of select="UPDATEDBY"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal" width="170pt">
              <fo:block>
                <xsl:value-of select="COLUMN"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal" width="60pt">
              <fo:block>
                <xsl:value-of select="PKVALUE"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal">
              <fo:block>
                <xsl:value-of select="FROMVALUE"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal">
              <fo:block>
                <xsl:value-of select="TOVALUE"/>
              </fo:block>
            </fo:table-cell>
            </fo:table-row>
          </xsl:for-each>
        </fo:table-body>
      </fo:table>
    </fo:block>
	
	<!-- ************************************ EXTERNALREFERENCES SECTION ************************************ -->
  	<fo:block font-size="14pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" color="#008080" font-weight="bold" space-before="10pt">
      <xsl:text>EXTERNAL REFERENCE SUMMARY</xsl:text>    
    </fo:block>
    <fo:block font-size="8pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" line-height="13pt" border-width="1pt" border-style="solid" border-color="#CCCCCC">
      <fo:table margin="3pt">
        <fo:table-body>
          <fo:table-row>
            <fo:table-cell margin="3pt" width="100pt">
              <fo:block font-weight="bold" color="#FF8040">Update TS</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="30pt">
              <fo:block font-weight="bold" color="#FF8040">Action</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="80pt">
              <fo:block font-weight="bold" color="#FF8040">Updated By</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="170pt">
              <fo:block font-weight="bold" color="#FF8040">Column</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="60pt">
              <fo:block font-weight="bold" color="#FF8040">PK1</fo:block>
            </fo:table-cell>
            <fo:table-cell>
              <fo:block font-weight="bold" color="#FF8040">From</fo:block>
            </fo:table-cell>
            <fo:table-cell>
              <fo:block font-weight="bold" color="#FF8040">To</fo:block>
            </fo:table-cell>
          </fo:table-row>
		  
		  <xsl:for-each select="/ROWSET/ROW/REPORT/EXTERNALREFERENCES/EXTERNALREFERENCES_T">
            <xsl:variable name="EXTERNALREFERENCES_T" select="."/> 
          <fo:table-row space-after="10pt">
            <fo:table-cell font-weight="normal" width="100pt">
              <fo:block>
                <xsl:value-of select="UPDATEDTS"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal" width="30pt">
              <fo:block>
                <xsl:value-of select="ACTION"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal" width="80pt">
              <fo:block>
                <xsl:value-of select="UPDATEDBY"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal" width="170pt">
              <fo:block>
                <xsl:value-of select="COLUMN"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal" width="60pt">
              <fo:block>
                <xsl:value-of select="PKVALUE"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal">
              <fo:block>
                <xsl:value-of select="FROMVALUE"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal">
              <fo:block>
                <xsl:value-of select="TOVALUE"/>
              </fo:block>
            </fo:table-cell>
            </fo:table-row>
          </xsl:for-each>
        </fo:table-body>
      </fo:table>
    </fo:block>
	
	<!-- ************************************ ACTIVITY SECTION ************************************ -->
  	<fo:block font-size="14pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" color="#008080" font-weight="bold" space-before="10pt">
      <xsl:text>ACTIVITY SUMMARY</xsl:text>    
    </fo:block>
    <fo:block font-size="8pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" line-height="13pt" border-width="1pt" border-style="solid" border-color="#CCCCCC">
      <fo:table margin="3pt">
        <fo:table-body>
          <fo:table-row>
            <fo:table-cell margin="3pt" width="100pt">
              <fo:block font-weight="bold" color="#FF8040">Update TS</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="30pt">
              <fo:block font-weight="bold" color="#FF8040">Action</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="80pt">
              <fo:block font-weight="bold" color="#FF8040">Updated By</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="170pt">
              <fo:block font-weight="bold" color="#FF8040">Column</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="60pt">
              <fo:block font-weight="bold" color="#FF8040">PK1</fo:block>
            </fo:table-cell>
            <fo:table-cell>
              <fo:block font-weight="bold" color="#FF8040">From</fo:block>
            </fo:table-cell>
            <fo:table-cell>
              <fo:block font-weight="bold" color="#FF8040">To</fo:block>
            </fo:table-cell>
          </fo:table-row>
		  
		  <xsl:for-each select="/ROWSET/ROW/REPORT/ACTIVITY/ACTIVITY_T">
            <xsl:variable name="ACTIVITY_T" select="."/> 
          <fo:table-row space-after="10pt">
            <fo:table-cell font-weight="normal" width="100pt">
              <fo:block>
                <xsl:value-of select="UPDATEDTS"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal" width="30pt">
              <fo:block>
                <xsl:value-of select="ACTION"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal" width="80pt">
              <fo:block>
                <xsl:value-of select="UPDATEDBY"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal" width="170pt">
              <fo:block>
                <xsl:value-of select="COLUMN"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal" width="60pt">
              <fo:block>
                <xsl:value-of select="PKVALUE"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal">
              <fo:block>
                <xsl:value-of select="FROMVALUE"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal">
              <fo:block>
                <xsl:value-of select="TOVALUE"/>
              </fo:block>
            </fo:table-cell>
            </fo:table-row>
          </xsl:for-each>
        </fo:table-body>
      </fo:table>
    </fo:block>

    <!-- ************************************ CONTACT ************************************ -->

    <fo:block font-size="14pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" color="#008080" font-weight="bold" space-before="10pt">
      <xsl:text>CONTACT</xsl:text>      
    </fo:block>
    <fo:block font-size="8pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" line-height="13pt" border-width="1pt" border-style="solid" border-color="#CCCCCC">
      <fo:table margin="3pt">
        <fo:table-body>
          <fo:table-row>
            <fo:table-cell margin="3pt" width="100pt">
              <fo:block font-weight="bold" color="#FF8040">Update TS</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="30pt">
              <fo:block font-weight="bold" color="#FF8040">Action</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="80pt">
              <fo:block font-weight="bold" color="#FF8040">Updated By</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="170pt">
              <fo:block font-weight="bold" color="#FF8040">Column</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="60pt">
              <fo:block font-weight="bold" color="#FF8040">PK1</fo:block>
            </fo:table-cell>
            <fo:table-cell>
              <fo:block font-weight="bold" color="#FF8040">From</fo:block>
            </fo:table-cell>
            <fo:table-cell>
              <fo:block font-weight="bold" color="#FF8040">To</fo:block>
            </fo:table-cell>
          </fo:table-row>
          <xsl:for-each select="/ROWSET/ROW/REPORT/CONTACTS/CONTACTS_T">
            <xsl:variable name="CONTACTS_T" select="."/> 
          <fo:table-row space-after="10pt">
            <fo:table-cell font-weight="normal" width="100pt">
              <fo:block>
                <xsl:value-of select="UPDATEDTS"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal" width="30pt">
              <fo:block>
                <xsl:value-of select="ACTION"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal" width="80pt">
              <fo:block>
                <xsl:value-of select="UPDATEDBY"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal" width="170pt">
              <fo:block>
                <xsl:value-of select="COLUMN"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal" width="60pt">
              <fo:block>
                <xsl:value-of select="PKVALUE"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal">
              <fo:block>
                <xsl:value-of select="FROMVALUE"/>
              </fo:block>
            </fo:table-cell>
            <fo:table-cell font-weight="normal">
              <fo:block>
                <xsl:value-of select="TOVALUE"/>
              </fo:block>
            </fo:table-cell>
            </fo:table-row>
          </xsl:for-each>
        </fo:table-body>
      </fo:table>
    </fo:block>

    <!-- ************************************ PATIENT ************************************ -->

    <fo:block font-size="14pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" color="#008080" font-weight="bold" space-before="10pt">
      <xsl:text>PATIENT</xsl:text>
    </fo:block>
    <fo:block font-size="8pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" line-height="13pt" border-width="1pt" border-style="solid" border-color="#CCCCCC">
      <fo:table margin="3pt">
        <fo:table-body>
          <fo:table-row>
            <fo:table-cell margin="3pt" width="100pt">
              <fo:block font-weight="bold" color="#FF8040">Update TS</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="30pt">
              <fo:block font-weight="bold" color="#FF8040">Action</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="80pt">
              <fo:block font-weight="bold" color="#FF8040">Updated By</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="170pt">
              <fo:block font-weight="bold" color="#FF8040">Column</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="60pt">
              <fo:block font-weight="bold" color="#FF8040">PK1</fo:block>
            </fo:table-cell>
            <fo:table-cell>
              <fo:block font-weight="bold" color="#FF8040">From</fo:block>
            </fo:table-cell>
            <fo:table-cell>
              <fo:block font-weight="bold" color="#FF8040">To</fo:block>
            </fo:table-cell>
          </fo:table-row>
          <xsl:for-each select="/ROWSET/ROW/REPORT/PATIENT/PATIENT_T">
            <xsl:variable name="PATIENT_T" select="."/>
            <fo:table-row space-after="10pt">
              <fo:table-cell font-weight="normal" width="100pt">
                <fo:block>
                  <xsl:value-of select="UPDATEDTS"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal" width="30pt">
                <fo:block>
                  <xsl:value-of select="ACTION"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal" width="80pt">
                <fo:block>
                  <xsl:value-of select="UPDATEDBY"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal" width="170pt">
                <fo:block>
                  <xsl:value-of select="COLUMN"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal" width="60pt">
                <fo:block>
                  <xsl:value-of select="PKVALUE"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal">
                <fo:block>
                  <xsl:value-of select="FROMVALUE"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal">
                <fo:block>
                  <xsl:value-of select="TOVALUE"/>
                </fo:block>
              </fo:table-cell>
            </fo:table-row>
          </xsl:for-each>
        </fo:table-body>
      </fo:table>
    </fo:block>

    <!-- ************************************ PRODUCT ************************************ -->

    <fo:block font-size="14pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" color="#008080" font-weight="bold" space-before="10pt">
      <xsl:text>PRODUCT</xsl:text>
    </fo:block>
    <fo:block font-size="8pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" line-height="13pt" border-width="1pt" border-style="solid" border-color="#CCCCCC">
      <fo:table margin="3pt">
        <fo:table-body>
          <fo:table-row>
            <fo:table-cell margin="3pt" width="100pt">
              <fo:block font-weight="bold" color="#FF8040">Update TS</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="30pt">
              <fo:block font-weight="bold" color="#FF8040">Action</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="80pt">
              <fo:block font-weight="bold" color="#FF8040">Updated By</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="170pt">
              <fo:block font-weight="bold" color="#FF8040">Column</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="60pt">
              <fo:block font-weight="bold" color="#FF8040">PK1</fo:block>
            </fo:table-cell>
            <fo:table-cell>
              <fo:block font-weight="bold" color="#FF8040">From</fo:block>
            </fo:table-cell>
            <fo:table-cell>
              <fo:block font-weight="bold" color="#FF8040">To</fo:block>
            </fo:table-cell>
          </fo:table-row>
          <xsl:for-each select="/ROWSET/ROW/REPORT/PRODUCT/PRODUCT_T">
            <xsl:variable name="PRODUCT_T" select="."/>
            <fo:table-row space-after="10pt">
              <fo:table-cell font-weight="normal" width="100pt">
                <fo:block>
                  <xsl:value-of select="UPDATEDTS"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal" width="30pt">
                <fo:block>
                  <xsl:value-of select="ACTION"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal" width="80pt">
                <fo:block>
                  <xsl:value-of select="UPDATEDBY"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal" width="170pt">
                <fo:block>
                  <xsl:value-of select="COLUMN"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal" width="60pt">
                <fo:block>
                  <xsl:value-of select="PKVALUE"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal">
                <fo:block>
                  <xsl:value-of select="FROMVALUE"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal">
                <fo:block>
                  <xsl:value-of select="TOVALUE"/>
                </fo:block>
              </fo:table-cell>
            </fo:table-row>
          </xsl:for-each>
        </fo:table-body>
      </fo:table>
    </fo:block>

    <!-- ************************************ EVENTS ************************************ -->

    <fo:block font-size="14pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" color="#008080" font-weight="bold" space-before="10pt">
      <xsl:text>EVENTS</xsl:text>
    </fo:block>
    <fo:block font-size="8pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" line-height="13pt" border-width="1pt" border-style="solid" border-color="#CCCCCC">
      <fo:table margin="3pt">
        <fo:table-body>
          <fo:table-row>
            <fo:table-cell margin="3pt" width="100pt">
              <fo:block font-weight="bold" color="#FF8040">Update TS</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="30pt">
              <fo:block font-weight="bold" color="#FF8040">Action</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="80pt">
              <fo:block font-weight="bold" color="#FF8040">Updated By</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="170pt">
              <fo:block font-weight="bold" color="#FF8040">Column</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="60pt">
              <fo:block font-weight="bold" color="#FF8040">PK1</fo:block>
            </fo:table-cell>
            <fo:table-cell>
              <fo:block font-weight="bold" color="#FF8040">From</fo:block>
            </fo:table-cell>
            <fo:table-cell>
              <fo:block font-weight="bold" color="#FF8040">To</fo:block>
            </fo:table-cell>
          </fo:table-row>
          <xsl:for-each select="/ROWSET/ROW/REPORT/EVENT/EVENT_T">
            <xsl:variable name="EVENT_T" select="."/>
            <fo:table-row space-after="10pt">
              <fo:table-cell font-weight="normal" width="100pt">
                <fo:block>
                  <xsl:value-of select="UPDATEDTS"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal" width="30pt">
                <fo:block>
                  <xsl:value-of select="ACTION"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal" width="80pt">
                <fo:block>
                  <xsl:value-of select="UPDATEDBY"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal" width="170pt">
                <fo:block>
                  <xsl:value-of select="COLUMN"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal" width="60pt">
                <fo:block>
                  <xsl:value-of select="PKVALUE"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal">
                <fo:block>
                  <xsl:value-of select="FROMVALUE"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal">
                <fo:block>
                  <xsl:value-of select="TOVALUE"/>
                </fo:block>
              </fo:table-cell>
            </fo:table-row>
          </xsl:for-each>
        </fo:table-body>
      </fo:table>
    </fo:block>

    <!-- ************************************ ATTACHMENT ITEM ************************************ -->

    <fo:block font-size="14pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" color="#008080" font-weight="bold" space-before="10pt">
      <xsl:text>ATTACHMENT</xsl:text>
    </fo:block>
    <fo:block font-size="8pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" line-height="13pt" border-width="1pt" border-style="solid" border-color="#CCCCCC">
      <fo:table margin="3pt">
        <fo:table-body>
          <fo:table-row>
            <fo:table-cell margin="3pt" width="100pt">
              <fo:block font-weight="bold" color="#FF8040">Update TS</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="30pt">
              <fo:block font-weight="bold" color="#FF8040">Action</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="80pt">
              <fo:block font-weight="bold" color="#FF8040">Updated By</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="170pt">
              <fo:block font-weight="bold" color="#FF8040">Column</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="60pt">
              <fo:block font-weight="bold" color="#FF8040">PK1</fo:block>
            </fo:table-cell>
            <fo:table-cell>
              <fo:block font-weight="bold" color="#FF8040">From</fo:block>
            </fo:table-cell>
            <fo:table-cell>
              <fo:block font-weight="bold" color="#FF8040">To</fo:block>
            </fo:table-cell>
          </fo:table-row>
          <xsl:for-each select="/ROWSET/ROW/REPORT/ATTACHMENT/ATTACHMENT_T">
            <xsl:variable name="ATTACHMENT_T" select="."/>
            <fo:table-row space-after="10pt">
              <fo:table-cell font-weight="normal" width="100pt">
                <fo:block>
                  <xsl:value-of select="UPDATEDTS"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal" width="30pt">
                <fo:block>
                  <xsl:value-of select="ACTION"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal" width="80pt">
                <fo:block>
                  <xsl:value-of select="UPDATEDBY"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal" width="170pt">
                <fo:block>
                  <xsl:value-of select="COLUMN"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal" width="60pt">
                <fo:block>
                  <xsl:value-of select="PKVALUE"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal">
                <fo:block>
                  <xsl:value-of select="FROMVALUE"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal">
                <fo:block>
                  <xsl:value-of select="TOVALUE"/>
                </fo:block>
              </fo:table-cell>
            </fo:table-row>
          </xsl:for-each>
        </fo:table-body>
      </fo:table>
    </fo:block>	

	<!-- ************************************ REPORT COMMENTS ************************************ -->

    <fo:block font-size="14pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" color="#008080" font-weight="bold" space-before="10pt">
      <xsl:text>REPORT COMMENTS</xsl:text>
    </fo:block>
    <fo:block font-size="8pt" font-family="Arial,Times,MS Gothic,Gulim,MingLiU" line-height="13pt" border-width="1pt" border-style="solid" border-color="#CCCCCC">
      <fo:table margin="3pt">
        <fo:table-body>
          <fo:table-row>
            <fo:table-cell margin="3pt" width="100pt">
              <fo:block font-weight="bold" color="#FF8040">Update TS</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="30pt">
              <fo:block font-weight="bold" color="#FF8040">Action</fo:block>
            </fo:table-cell>
            <fo:table-cell margin="3pt" width="80pt">
              <fo:block font-weight="bold" color="#FF8040">Updated By</fo:block>
            </fo:table-cell>
            <fo:table-cell>
              <fo:block font-weight="bold" color="#FF8040">Comments</fo:block>
            </fo:table-cell>
          </fo:table-row>
          <xsl:for-each select="/ROWSET/ROW/REPORT/REPORTCOMMENTS/REPORTCOMMENTS_T">
            <xsl:variable name="REPORTCOMMENTS_T" select="."/>
            <fo:table-row space-after="10pt">
              <fo:table-cell font-weight="normal" width="100pt">
                <fo:block>
                  <xsl:value-of select="UPDATEDTS"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal" width="30pt">
                <fo:block>
                  <xsl:value-of select="ACTION"/>
                </fo:block>
              </fo:table-cell>
              <fo:table-cell font-weight="normal" width="80pt">
                <fo:block>
                  <xsl:value-of select="UPDATEDBY"/>
                </fo:block>
              </fo:table-cell>            
              <fo:table-cell font-weight="normal">
                <fo:block>
                  <xsl:value-of select="TOVALUE"/>
                </fo:block>
              </fo:table-cell>
            </fo:table-row>
          </xsl:for-each>
        </fo:table-body>
      </fo:table>
    </fo:block>
	
  </fo:flow>
</fo:page-sequence>

</fo:root>
</xsl:template>

 
</xsl:stylesheet>