<ROWSET>
  <ROW>
    <UI_GROUP NAME="Activities" UI_GROUP_ID="Activities">
      <FIELDS NAME="Type" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="ACTIVITY_TYPE"
              SERVICE_NAME="REPORT_ACTIVITY_TYPE" DB_OBJECT_NAME="LAU_REPORT_ACTIVITIES" FIELD_ID="301"></FIELDS>
      <FIELDS NAME="Description" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="ACTIVITY_DESCRIPTION"
              DB_OBJECT_NAME="LAU_REPORT_ACTIVITIES" FIELD_ID="302"></FIELDS>
      <FIELDS NAME="Activity Date" UI_COMPONENT_NAME="dbDate" DB_FIELD_NAME="ACTIVITY_DATE"
              DB_OBJECT_NAME="LAU_REPORT_ACTIVITIES" FIELD_ID="303"></FIELDS>
      <FIELDS NAME="Priority" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="PRIORITY" SERVICE_NAME="PRIORITY"
              DB_OBJECT_NAME="LAU_REPORT_ACTIVITIES" FIELD_ID="304"></FIELDS>
      <FIELDS NAME="Reason" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="ACTIVITY_REASON"
              SERVICE_NAME="REPORT_ACTIVITY_REASON" DB_OBJECT_NAME="LAU_REPORT_ACTIVITIES" FIELD_ID="308"></FIELDS>
      <FIELDS NAME="Assigned to" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="ASSIGNED_TO_USER" SERVICE_NAME="LAU_USERS"
              DB_OBJECT_NAME="LAU_REPORT_ACTIVITIES" FIELD_ID="309"></FIELDS>
      <FIELDS NAME="Due Date" UI_COMPONENT_NAME="dbDate" DB_FIELD_NAME="DUE_DATE" DB_OBJECT_NAME="LAU_REPORT_ACTIVITIES"
              FIELD_ID="310"></FIELDS>
      <FIELDS NAME="Completed" UI_COMPONENT_NAME="dbDate" DB_FIELD_NAME="COMPLETION_DATE"
              DB_OBJECT_NAME="LAU_REPORT_ACTIVITIES" FIELD_ID="311"></FIELDS>
      <FIELDS NAME="Comment" UI_COMPONENT_NAME="TextArea" DB_FIELD_NAME="CUSTOM_COMMENT_01"
              DB_OBJECT_NAME="LAU_REPORT_ACTIVITIES" FIELD_ID="312"></FIELDS>
      <FIELDS NAME="Completion Comment" UI_COMPONENT_NAME="TextArea" DB_FIELD_NAME="CUSTOM_COMMENT_02"
              DB_OBJECT_NAME="LAU_REPORT_ACTIVITIES" FIELD_ID="313"></FIELDS>
      <FIELDS NAME="Activity Direction" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="DIRECTION"
              SERVICE_NAME="ACTIVITY_DIRECTION" DB_OBJECT_NAME="LAU_REPORT_ACTIVITIES" FIELD_ID="316"></FIELDS>
    </UI_GROUP>
  </ROW>
  <ROW>
    <UI_GROUP NAME="Attachments" UI_GROUP_ID="Attachments">
      <FIELDS NAME="Attachment File Name" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="FILE_NAME"
              DB_OBJECT_NAME="LAU_REPORT_ATTACHMENTS" FIELD_ID="701"></FIELDS>
      <FIELDS NAME="Document Name" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="DOCUMENT_NAME"
              DB_OBJECT_NAME="LAU_REPORT_ATTACHMENTS" FIELD_ID="702"></FIELDS>
      <FIELDS NAME="Document Type" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="DOCUMENT_TYPE"
              DB_OBJECT_NAME="LAU_REPORT_ATTACHMENTS" FIELD_ID="703"></FIELDS>
    </UI_GROUP>
  </ROW>
  <ROW>
    <UI_GROUP NAME="Contacts" UI_GROUP_ID="Contacts">
      <FIELDS NAME="Contact Type" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="CONTACT_TYPE" SERVICE_NAME="CONTACT_TYPE"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="501"></FIELDS>
      <FIELDS NAME="Title" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="CONTACT_TITLE" SERVICE_NAME="PERSONAL_TITLE"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="502"></FIELDS>
      <FIELDS NAME="Last Name" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_LAST_NAME"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="503"></FIELDS>
      <FIELDS NAME="First Name" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_FIRST_NAME"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="504"></FIELDS>
      <FIELDS NAME="Middle" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_MIDDLE_NAME"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="505"></FIELDS>
      <FIELDS NAME="Confidential" UI_COMPONENT_NAME="CheckBox" DB_FIELD_NAME="CONTACT_CONFIDENTIAL_FLAG"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="506"></FIELDS>
      <FIELDS NAME="Company" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_ORGANIZATION"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="507"></FIELDS>
      <FIELDS NAME="Department" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_DEPARTMENT"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="508"></FIELDS>
      <FIELDS NAME="Street Address" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_ADDRESS1"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="509"></FIELDS>
      <FIELDS NAME="Street Address 2" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_ADDRESS2"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="510"></FIELDS>
      <FIELDS NAME="Street Address 3" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_ADDRESS3"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="511"></FIELDS>
      <FIELDS NAME="City" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_CITY" DB_OBJECT_NAME="LAU_CONTACT"
              FIELD_ID="512"></FIELDS>
      <FIELDS NAME="State" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="CONTACT_STATE" SERVICE_NAME="STATES"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="513"></FIELDS>
      <FIELDS NAME="Country" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="CONTACT_COUNTRY" SERVICE_NAME="COUNTRIES"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="514"></FIELDS>
      <FIELDS NAME="Postal Code" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_POSTAL_CODE"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="515"></FIELDS>
      <FIELDS NAME="Phone country code" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_PHONE_CC"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="516"></FIELDS>
      <FIELDS NAME="Phone Number" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_PHONE_NUMBER"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="517"></FIELDS>
      <FIELDS NAME="Phone extension" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_PHONE_EXT"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="518"></FIELDS>
      <FIELDS NAME="Fax country code" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_FAX_CC"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="519"></FIELDS>
      <FIELDS NAME="Fax number" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_FAX_NUMBER"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="520"></FIELDS>
      <FIELDS NAME="Fax extension" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_FAX_EXT"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="521"></FIELDS>
      <FIELDS NAME="Mobile country code" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_MOBILE_CC"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="522"></FIELDS>
      <FIELDS NAME="Mobile number" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_MOBILE_NUMBER"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="523"></FIELDS>
      <FIELDS NAME="Mobile extension" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_MOBILE_EXT"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="524"></FIELDS>
      <FIELDS NAME="Email" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CONTACT_EMAIL" DB_OBJECT_NAME="LAU_CONTACT"
              FIELD_ID="525"></FIELDS>
      <FIELDS NAME="Reporter Type" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="REPORTER_TYPE"
              SERVICE_NAME="REPORTER_TYPE" DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="526"></FIELDS>
      <FIELDS NAME="Occupation" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="CONTACT_OCCUPATION"
              SERVICE_NAME="REPORTER_OCCUPATION" DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="527"></FIELDS>
      <FIELDS NAME="Occupation Other" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="OTHER_OCCUPATION_DESC"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="528"></FIELDS>
      <FIELDS NAME="Specialty" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="CONTACT_SPECIALTY" SERVICE_NAME="SPECIALTY"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="529"></FIELDS>
      <FIELDS NAME="FDA District Code" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CUSTOM_TEXT_01"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="530"></FIELDS>
      <FIELDS NAME="FDA District Code 2" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CUSTOM_TEXT_02"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="531"></FIELDS>
      <FIELDS NAME="FDA District Code 3" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CUSTOM_TEXT_03"
              DB_OBJECT_NAME="LAU_CONTACT" FIELD_ID="532"></FIELDS>
      <FIELDS NAME="Comments" UI_COMPONENT_NAME="TextArea" DB_FIELD_NAME="CONTACT_COMMENT" DB_OBJECT_NAME="LAU_CONTACT"
              FIELD_ID="533"></FIELDS>
    </UI_GROUP>
  </ROW>
  <ROW>
    <UI_GROUP NAME="Narratives" UI_GROUP_ID="Narratives">
      <FIELDS NAME="Narrative Type" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="NARRATIVE_TEXT_TYPE"
              SERVICE_NAME="NARRATIVE_TYPE" DB_OBJECT_NAME="LAU_NARRATIVE_TEXT" FIELD_ID="601"></FIELDS>
      <FIELDS NAME="Releasable" UI_COMPONENT_NAME="CheckBox" DB_FIELD_NAME="PUBLIC_CONTENT_FLAG"
              DB_OBJECT_NAME="LAU_NARRATIVE_TEXT" FIELD_ID="602"></FIELDS>
      <FIELDS NAME="Narrative Text" UI_COMPONENT_NAME="TextArea" DB_FIELD_NAME="NARRATIVE_TEXT"
              DB_OBJECT_NAME="LAU_NARRATIVE_TEXT" FIELD_ID="603"></FIELDS>
    </UI_GROUP>
  </ROW>
  <ROW>
    <UI_GROUP NAME="Patients" UI_GROUP_ID="Patients">
      <FIELDS NAME="Patient ID" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="STUDY_PATIENT_ID"
              DB_OBJECT_NAME="LAU_PATIENT_DETAILS" FIELD_ID="401"></FIELDS>
      <FIELDS NAME="BirthDate" UI_COMPONENT_NAME="dbDate" DB_FIELD_NAME="PT_DOB" DB_OBJECT_NAME="LAU_PATIENT_DETAILS"
              FIELD_ID="402"></FIELDS>
      <FIELDS NAME="Age at event onset" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="PT_AGE"
              DB_OBJECT_NAME="LAU_PATIENT_DETAILS" FIELD_ID="403"></FIELDS>
      <FIELDS NAME="Age Unit" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="PT_AGE_UNITS" SERVICE_NAME="TIME_UNITS"
              DB_OBJECT_NAME="LAU_PATIENT_DETAILS" FIELD_ID="404"></FIELDS>
      <FIELDS NAME="Sex" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="PT_SEX" SERVICE_NAME="SEX"
              DB_OBJECT_NAME="LAU_PATIENT_DETAILS" FIELD_ID="405"></FIELDS>
      <FIELDS NAME="Weight" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="PT_WEIGHT" DB_OBJECT_NAME="LAU_PATIENT_DETAILS"
              FIELD_ID="406"></FIELDS>
      <FIELDS NAME="Weight Unit" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="PT_WEIGHT_UNITS"
              SERVICE_NAME="WEIGHT_UNITS" DB_OBJECT_NAME="LAU_PATIENT_DETAILS" FIELD_ID="407"></FIELDS>
      <FIELDS NAME="Patient Died" UI_COMPONENT_NAME="CheckBox" DB_FIELD_NAME="PATIENT_DIED_FLAG"
              DB_OBJECT_NAME="LAU_PATIENT_DETAILS" FIELD_ID="408"></FIELDS>
      <FIELDS NAME="Date of Death" UI_COMPONENT_NAME="dbDate" DB_FIELD_NAME="DEATH_DATE"
              DB_OBJECT_NAME="LAU_PATIENT_DETAILS" FIELD_ID="409"></FIELDS>
      <FIELDS NAME="Life Threatening" UI_COMPONENT_NAME="CheckBox" DB_FIELD_NAME="LIFE_THREATENING_FLAG"
              DB_OBJECT_NAME="LAU_PATIENT_DETAILS" FIELD_ID="410"></FIELDS>
      <FIELDS NAME="Hospitalization" UI_COMPONENT_NAME="CheckBox" DB_FIELD_NAME="HOSPITALIZATION_FLAG"
              DB_OBJECT_NAME="LAU_PATIENT_DETAILS" FIELD_ID="411"></FIELDS>
      <FIELDS NAME="Hospitalization Nature" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="HOSPITALIZATION_NATURE"
              SERVICE_NAME="HOSPITALIZATION_TYPE" DB_OBJECT_NAME="LAU_PATIENT_DETAILS" FIELD_ID="412"></FIELDS>
      <FIELDS NAME="Hospitalization From" UI_COMPONENT_NAME="dbDate" DB_FIELD_NAME="HOSPITALIZED_FROM_DATE"
              DB_OBJECT_NAME="LAU_PATIENT_DETAILS" FIELD_ID="413"></FIELDS>
      <FIELDS NAME="Hospitalization To" UI_COMPONENT_NAME="dbDate" DB_FIELD_NAME="HOSPITALIZED_TO_DATE"
              DB_OBJECT_NAME="LAU_PATIENT_DETAILS" FIELD_ID="414"></FIELDS>
      <FIELDS NAME="Required Intervention" UI_COMPONENT_NAME="CheckBox" DB_FIELD_NAME="REQUIRED_INTERVENTION"
              DB_OBJECT_NAME="LAU_PATIENT_DETAILS" FIELD_ID="415"></FIELDS>
      <FIELDS NAME="Disability" UI_COMPONENT_NAME="CheckBox" DB_FIELD_NAME="DISABILITY_FLAG"
              DB_OBJECT_NAME="LAU_PATIENT_DETAILS" FIELD_ID="416"></FIELDS>
      <FIELDS NAME="Congenital Anomaly" UI_COMPONENT_NAME="CheckBox" DB_FIELD_NAME="CONGENITAL_ANOMALY_FLAG"
              DB_OBJECT_NAME="LAU_PATIENT_DETAILS" FIELD_ID="417"></FIELDS>
      <FIELDS NAME="Other Serious (Medically Important Event)" UI_COMPONENT_NAME="CheckBox"
              DB_FIELD_NAME="MEDICALLY_IMPORTANT_EVENT" DB_OBJECT_NAME="LAU_PATIENT_DETAILS" FIELD_ID="418"></FIELDS>
      <FIELDS NAME="Other Specify" UI_COMPONENT_NAME="TextArea" DB_FIELD_NAME="OTHER_SERIOUSNESS_DESC"
              DB_OBJECT_NAME="LAU_PATIENT_DETAILS" FIELD_ID="419"></FIELDS>
    </UI_GROUP>
  </ROW>
  <ROW>
    <UI_GROUP NAME="Products" UI_GROUP_ID="Products">
      <FIELDS NAME="Brand" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="TRADE_NAME" DB_OBJECT_NAME="LAU_PRODUCTS"
              FIELD_ID="801"></FIELDS>
      <FIELDS NAME="Generic" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="GENERIC_NAME" DB_OBJECT_NAME="LAU_PRODUCTS"
              FIELD_ID="802"></FIELDS>
      <FIELDS NAME="Product Code" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="PRODUCT_CODE"
              SERVICE_NAME="PRODUCT_CODES" DB_OBJECT_NAME="LAU_PRODUCTS" FIELD_ID="803"></FIELDS>
      <FIELDS NAME="Model #" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="MODEL_NUMBER"
              DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="811"></FIELDS>
      <FIELDS NAME="Catalog #" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="CATALOG_NUMBER"
              DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="812"></FIELDS>
      <FIELDS NAME="Serial #" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="SERIAL_NUMBER"
              DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="813"></FIELDS>
      <FIELDS NAME="Other #" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="OTHER_DEVICE_NUMBER"
              DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="814"></FIELDS>
      <FIELDS NAME="Lot #" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="LOT_NUMBER" DB_OBJECT_NAME="LAU_DEVICE_DETAILS"
              FIELD_ID="815"></FIELDS>
      <FIELDS NAME="Expiration Date" UI_COMPONENT_NAME="dbDate" DB_FIELD_NAME="EXPIRATION_DATE"
              DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="816"></FIELDS>
      <FIELDS NAME="Manufactured Date" UI_COMPONENT_NAME="dbDate" DB_FIELD_NAME="MANUFACTURED_DATE"
              DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="817"></FIELDS>
      <FIELDS NAME="Device Age" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="DEVICE_AGE"
              DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="818"></FIELDS>
      <FIELDS NAME="Device Age Unit" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="DEVICE_AGE_UNITS"
              SERVICE_NAME="TIME_UNITS" DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="819"></FIELDS>
      <FIELDS NAME="Operator of Device" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="DEVICE_OPERATOR"
              SERVICE_NAME="DEVICE_OPERATOR" DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="820"></FIELDS>
      <FIELDS NAME="Implanted Date" UI_COMPONENT_NAME="dbDate" DB_FIELD_NAME="IMPLANT_DATE"
              DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="821"></FIELDS>
      <FIELDS NAME="Device Usage" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="DEVICE_USAGE" SERVICE_NAME="DEVICE_USAGE"
              DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="822"></FIELDS>
      <FIELDS NAME="Single Use Device?" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="SINGLE_USE_DEVICE"
              SERVICE_NAME="YESNONI" DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="823"></FIELDS>
      <FIELDS NAME="Device Available for Evaluation?" UI_COMPONENT_NAME="filterbox"
              DB_FIELD_NAME="DEVICE_AVAILABLE_FOR_EVAL" SERVICE_NAME="DEVICE_AVAILABLE"
              DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="824"></FIELDS>
      <FIELDS NAME="Device Evaluated by Mfg?" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="DEVICE_EVAL_BY_MFG"
              SERVICE_NAME="DEVICE_EVALUATED" DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="825"></FIELDS>
      <FIELDS NAME="Remedial Action Initiated" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="REMEDIAL_ACTION_TAKEN"
              SERVICE_NAME="REMEDIAL_ACTION_TYPE" DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="826"></FIELDS>
      <FIELDS NAME="Other (specify)" UI_COMPONENT_NAME="TextArea" DB_FIELD_NAME="DEVICE_OPERATOR_OTHER"
              DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="827"></FIELDS>
      <FIELDS NAME="Explanted Date" UI_COMPONENT_NAME="dbDate" DB_FIELD_NAME="EXPLANT_DATE"
              DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="828"></FIELDS>
      <FIELDS NAME="Reprocessed?" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="SINGLE_USE_DEVICE_REPROCESSED"
              SERVICE_NAME="YESNONI" DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="829"></FIELDS>
      <FIELDS NAME="Return Date" UI_COMPONENT_NAME="dbDate" DB_FIELD_NAME="DEVICE_RETURN_DATE"
              DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="830"></FIELDS>
      <FIELDS NAME="Reason Not Eval" UI_COMPONENT_NAME="TextArea" DB_FIELD_NAME="DEV_NOT_EVAL_REASON"
              DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="831"></FIELDS>
      <FIELDS NAME="Other Remedial Action" UI_COMPONENT_NAME="TextArea" DB_FIELD_NAME="REMEDIAL_ACTION_OTHER"
              DB_OBJECT_NAME="LAU_DEVICE_DETAILS" FIELD_ID="832"></FIELDS>
    </UI_GROUP>
  </ROW>
  <ROW>
    <UI_GROUP NAME="Report" UI_GROUP_ID="Report">
      <FIELDS NAME="CONTACT DATE" UI_COMPONENT_NAME="dbDate" DB_FIELD_NAME="REPORT_CONTACT_DATE"
              DB_OBJECT_NAME="LAU_REPORTS" FIELD_ID="101"></FIELDS>
      <FIELDS NAME="Follow Up #" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="SUBMITTED_FOLLOWUP_NUMBER"
              DB_OBJECT_NAME="LAU_REPORTS" FIELD_ID="104"></FIELDS>
      <FIELDS NAME="AE" UI_COMPONENT_NAME="CheckBox" DB_FIELD_NAME="ADVERSE_EVENT_FLAG" DB_OBJECT_NAME="LAU_REPORTS"
              FIELD_ID="105"></FIELDS>
      <FIELDS NAME="Product Problem" UI_COMPONENT_NAME="CheckBox" DB_FIELD_NAME="PRODUCT_COMPLAINT_FLAG"
              DB_OBJECT_NAME="LAU_REPORTS" FIELD_ID="106"></FIELDS>
      <FIELDS NAME="FOLLOW-UP TYPE" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="FOLLOW_UP_TYPE"
              SERVICE_NAME="FOLLOW_UP_TYPE" DB_OBJECT_NAME="LAU_REPORTS" FIELD_ID="107"></FIELDS>
      <FIELDS NAME="REPORT ALERT" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="REPORT_ALERT" SERVICE_NAME="REPORT_ALERT"
              DB_OBJECT_NAME="LAU_REPORTS" FIELD_ID="108"></FIELDS>
      <FIELDS NAME="STATUS" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="REPORT_STATUS" SERVICE_NAME="REPORT_STATUS"
              DB_OBJECT_NAME="LAU_REPORTS" FIELD_ID="109"></FIELDS>
      <FIELDS NAME="REPORT REVIEW STATUS" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="REPORT_REVIEW_STATUS"
              SERVICE_NAME="REPORT_REVIEW_STATUS" DB_OBJECT_NAME="LAU_REPORTS" FIELD_ID="110"></FIELDS>
      <FIELDS NAME="Report Type" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="REPORT_INITIAL_OR_FOLLOWUP"
              SERVICE_NAME="REPORT_INITIAL_OR_FOLLOWUP" DB_OBJECT_NAME="LAU_REPORTS" FIELD_ID="111"></FIELDS>
      <FIELDS NAME="Type of Report" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="SUBMITTED_REPORT_TYPE"
              SERVICE_NAME="OTHER_SOURCE_TYPE" DB_OBJECT_NAME="LAU_REPORTS" FIELD_ID="201"></FIELDS>
      <FIELDS NAME="Date of Event" UI_COMPONENT_NAME="dbDate" DB_FIELD_NAME="DATE_OF_EVENT" DB_OBJECT_NAME="LAU_REPORTS"
              FIELD_ID="202"></FIELDS>
      <FIELDS NAME="Date of Report" UI_COMPONENT_NAME="dbDate" DB_FIELD_NAME="REPORT_RECEIVED_DATE"
              DB_OBJECT_NAME="LAU_REPORTS" FIELD_ID="203"></FIELDS>
      <FIELDS NAME="Death" UI_COMPONENT_NAME="CheckBox" DB_FIELD_NAME="DEV_REPORT_TYPE_DEATH"
              DB_OBJECT_NAME="LAU_DEVICE_REPORT_DETAILS" FIELD_ID="204"></FIELDS>
      <FIELDS NAME="Serious Injury" UI_COMPONENT_NAME="CheckBox" DB_FIELD_NAME="DEV_REPORT_TYPE_INJURY"
              DB_OBJECT_NAME="LAU_DEVICE_REPORT_DETAILS" FIELD_ID="205"></FIELDS>
      <FIELDS NAME="Malfunction" UI_COMPONENT_NAME="CheckBox" DB_FIELD_NAME="DEV_REPORT_TYPE_MALFUNCTION"
              DB_OBJECT_NAME="LAU_DEVICE_REPORT_DETAILS" FIELD_ID="206"></FIELDS>
      <FIELDS NAME="Other" UI_COMPONENT_NAME="CheckBox" DB_FIELD_NAME="DEV_REPORT_TYPE_OTHER_SPECIFY"
              DB_OBJECT_NAME="LAU_DEVICE_REPORT_DETAILS" FIELD_ID="207"></FIELDS>
      <FIELDS NAME="Report Also Sent to FDA" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="REPORT_SENT_TO_FDA"
              SERVICE_NAME="YESNOUNKNA" DB_OBJECT_NAME="LAU_DEVICE_REPORT_DETAILS" FIELD_ID="208"></FIELDS>
      <FIELDS NAME="Date Sent to FDA" UI_COMPONENT_NAME="dbDate" DB_FIELD_NAME="REPORT_SENT_TO_FDA_DATE"
              DB_OBJECT_NAME="LAU_DEVICE_REPORT_DETAILS" FIELD_ID="209"></FIELDS>
      <FIELDS NAME="Report Also Sent to Manufacturer" UI_COMPONENT_NAME="filterbox" DB_FIELD_NAME="REPORT_SENT_TO_MFG"
              SERVICE_NAME="YESNOUNKNA" DB_OBJECT_NAME="LAU_DEVICE_REPORT_DETAILS" FIELD_ID="210"></FIELDS>
      <FIELDS NAME="Date Sent to Manufacturer" UI_COMPONENT_NAME="dbDate" DB_FIELD_NAME="REPORT_SENT_TO_MFG_DATE"
              DB_OBJECT_NAME="LAU_DEVICE_REPORT_DETAILS" FIELD_ID="211"></FIELDS>
      <FIELDS NAME="Recipient Code" UI_COMPONENT_NAME="TextInput" DB_FIELD_NAME="REPORT_RECIPIENT_CODE"
              DB_OBJECT_NAME="LAU_DEVICE_REPORT_DETAILS" FIELD_ID="212"></FIELDS>
      <FIELDS NAME="Report Also Sent to User Facility" UI_COMPONENT_NAME="filterbox"
              DB_FIELD_NAME="REPORT_SENT_TO_USER_FACILITY" SERVICE_NAME="YESNOUNKNA"
              DB_OBJECT_NAME="LAU_DEVICE_REPORT_DETAILS" FIELD_ID="213"></FIELDS>
      <FIELDS NAME="Report Also Sent to User Distributor" UI_COMPONENT_NAME="filterbox"
              DB_FIELD_NAME="REPORT_SENT_TO_DIST" SERVICE_NAME="YESNOUNKNA" DB_OBJECT_NAME="LAU_DEVICE_REPORT_DETAILS"
              FIELD_ID="214"></FIELDS>
      <FIELDS NAME="Distributor Aware Date" UI_COMPONENT_NAME="dbDate" DB_FIELD_NAME="DISTRIBUTOR_AWARE_DATE"
              DB_OBJECT_NAME="LAU_DEVICE_REPORT_DETAILS" FIELD_ID="215"></FIELDS>
      <FIELDS NAME="Distributor Report Date" UI_COMPONENT_NAME="dbDate" DB_FIELD_NAME="DISTRIBUTOR_REPORT_DATE"
              DB_OBJECT_NAME="LAU_DEVICE_REPORT_DETAILS" FIELD_ID="216"></FIELDS>
      <FIELDS NAME="Report Comments" UI_COMPONENT_NAME="TextArea" DB_FIELD_NAME="NARRATIVE_TEXT"
              DB_OBJECT_NAME="LAU_NARRATIVE_TEXT" FIELD_ID="217"></FIELDS>
    </UI_GROUP>
  </ROW>
</ROWSET>
