<ROWSET>
 <ROW>
  <CODE>1</CODE>
  <CODE_VALUE>IN LIST</CODE_VALUE>
 </ROW>
 <ROW>
  <CODE>2</CODE>
  <CODE_VALUE>NOT IN LIST</CODE_VALUE>
 </ROW>
 <ROW>
  <CODE>3</CODE>
  <CODE_VALUE>EQUAL TO</CODE_VALUE>
 </ROW>
  <ROW>
  <CODE>4</CODE>
  <CODE_VALUE>NOT EQUAL TO</CODE_VALUE>
 </ROW>
 <ROW>
  <CODE>5</CODE>
  <CODE_VALUE>IS NULL</CODE_VALUE>
 </ROW>
</ROWSET>