
<ROWSET>
 <ROW>
  <CODE>AND</CODE>
  <CODE_VALUE>ALL</CODE_VALUE>
 </ROW>
 <ROW>
  <CODE>OR</CODE>
  <CODE_VALUE>AT LEAST ONE</CODE_VALUE>
 </ROW>
 <ROW>
  <CODE>NOT OR</CODE>
  <CODE_VALUE>NOT ANY</CODE_VALUE>
 </ROW>
 <ROW>
  <CODE>NOT AND</CODE>
  <CODE_VALUE>NONE</CODE_VALUE>
 </ROW>
 
</ROWSET>